spring.application.name=api-gateway

server.port=8000

# Virtual Threads
spring.threads.virtual.enabled=true

# Downstream Services
app.services.order=${ORDER_SERVICE_URL:http://localhost:8001}
app.services.inventory=${INVENTORY_URL:http://localhost:8002}
app.services.auth=${AUTH_URL:http://localhost:8003}
app.services.cart=${CART_URL:http://localhost:8004}
app.services.payment=${PAYMENT_URL:http://localhost:8005}

# Logging
logging.level.com.ecommerce.gateway=DEBUG
