apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: nirshah77/cart-service:latest
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: microservices-config
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
