server.port=8003

# Database configuration (SQLite)
spring.datasource.url=jdbc:sqlite:${DB_PATH:db/app.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Optimize concurrency with Java 21 Virtual Threads
spring.threads.virtual.enabled=true
