apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  INVENTORY_URL: "http://inventory-service:8002"
  AUTH_URL: "http://auth-service:8003"
  CART_URL: "http://cart-service:8004"
  PAYMENT_URL: "http://payment-service:8005"
  REDIS_URL: "redis://redis-service:6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
