spring.application.name=payment-service

server.port=8005

# Virtual Threads
spring.threads.virtual.enabled=true

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Databases
db.auth.url=jdbc:sqlite:${AUTH_DB_PATH:db/app.db}
db.inventory.url=jdbc:sqlite:${INVENTORY_DB_PATH:inventory_service/inventory.db}

# Cart service URL
cart.url=${CART_URL:http://localhost:8004}
