server.port=8004

# Redis Configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

# Inventory Service URL
inventory.service.url=${INVENTORY_URL:http://localhost:8002}

# Enable Virtual Threads
spring.threads.virtual.enabled=true

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Saga toggle
saga.enabled=${SAGA_ENABLED:false}
