apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-consumer
  template:
    metadata:
      labels:
        app: inventory-consumer
    spec:
      containers:
        - name: inventory-consumer
          image: nirshah77/inventory-service:latest
          env:
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: "none"
          envFrom:
            - configMapRef:
                name: microservices-config
          volumeMounts:
            - name: inventory-db-storage
              mountPath: /app/inventory_service
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 1024Mi
      volumes:
        - name: inventory-db-storage
          persistentVolumeClaim:
            claimName: inventory-db-pvc
