server.port=8004

# Redis Configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

# Inventory Service URL
inventory.service.url=${INVENTORY_URL:http://localhost:8002}

# Enable Virtual Threads
spring.threads.virtual.enabled=true
