# .github/workflows/ci.yml

name: Build and Push Microservices

# When does this pipeline run?
on:
  push:
    branches:
      - main          # only on pushes to main, not feature branches

jobs:

  # ─────────────────────────────────────────────
  # JOB 1: Figure out what changed
  # This job runs first, always, on every push.
  # It outputs true/false for each service.
  # ─────────────────────────────────────────────
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      gateway:   ${{ steps.filter.outputs.gateway }}
      auth:      ${{ steps.filter.outputs.auth }}
      cart:      ${{ steps.filter.outputs.cart }}
      payment:   ${{ steps.filter.outputs.payment }}
      inventory: ${{ steps.filter.outputs.inventory }}
      consumer:  ${{ steps.filter.outputs.consumer }}
    steps:
      - uses: actions/checkout@v4   # checks out your repo code

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            gateway:
              - 'api_gateway/**'
              - 'requirements.txt'
              - 'docker-compose.yml'
            auth:
              - 'auth_service/**'
              - 'requirements.txt'
              - 'init_db.py'
            cart:
              - 'cart_service/**'
              - 'requirements.txt'
            payment:
              - 'payment_service/**'
              - 'requirements.txt'
              - 'init_db.py'
            inventory:
              - 'inventory_service/**'
              - 'requirements.txt'
            consumer:
              - 'inventory_service/consumer.py'
              - 'inventory_service/db.py'
              - 'requirements.txt'
              # consumer is a separate image but lives in inventory_service folder


  # ─────────────────────────────────────────────
  # JOB 2-7: One build job per service
  # Each job is identical in structure.
  # Only difference is the folder and image name.
  # needs: detect-changes means it waits for Job 1
  # if: ... means it only runs if that service changed
  # ─────────────────────────────────────────────

  build-gateway:
    needs: detect-changes
    if: needs.detect-changes.outputs.gateway == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api_gateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }}


  build-auth:
    needs: detect-changes
    if: needs.detect-changes.outputs.auth == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./auth_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}


  build-cart:
    needs: detect-changes
    if: needs.detect-changes.outputs.cart == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cart_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cart-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cart-service:${{ github.sha }}


  build-payment:
    needs: detect-changes
    if: needs.detect-changes.outputs.payment == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./payment_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:${{ github.sha }}


  build-inventory:
    needs: detect-changes
    if: needs.detect-changes.outputs.inventory == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./inventory_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:${{ github.sha }}


  build-consumer:
    needs: detect-changes
    if: needs.detect-changes.outputs.consumer == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./inventory_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/inventory-consumer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/inventory-consumer:${{ github.sha }}



  # ─────────────────────────────────────────────
  # JOB 8: Deploy to Kubernetes via Ansible
  # Executing K8s deployments through an Ansible Playbook
  # using Ansible Roles and Ansible Vault for secrets.
  # ─────────────────────────────────────────────
  ansible-deploy:
    needs: [build-gateway, build-auth, build-cart, build-payment, build-inventory, build-consumer]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Install Ansible and kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y ansible
          # Ensure kubectl is installed on the runner (usually it is, but just in case)
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Deploy Kubernetes Manifests via Ansible
        env:
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo "$VAULT_PASS" > ansible/vault_pass.txt
          ansible-playbook ansible/deploy_k8s.yml --vault-password-file ansible/vault_pass.txt

  local-deploy:
    needs: [build-gateway, build-auth, build-cart, build-payment, build-inventory, build-consumer]
    if: always()
    runs-on: self-hosted
    steps:
      - name: Restart Local Minikube Pods
        shell: powershell
        run: |
          kubectl rollout restart deployment api-gateway
          kubectl rollout restart deployment auth-service
          kubectl rollout restart deployment cart-service
          kubectl rollout restart deployment payment-service
          kubectl rollout restart deployment inventory-service
          kubectl rollout restart deployment inventory-consumer
